

var image_names = [
    "assets/1_Kish_Tablet.png",
    "assets/2_Narmer_Palette.jpeg",
    "assets/Instructions_of_Shurrupak.jpg",
    "assets/4_Diary_of_Merer.jpeg",
    "assets/3_Palermo_Stone.png",
    "assets/5_Istanbul_2461.jpeg",
    "assets/Code_of_Hammurabi.png",
    "assets/6_Complaint_tablet_to_Ea-nāṣir.png",
    "assets/Gilgamesh_Dream_Tablet.jpg",
    "assets/7_Akkadian_Cuneiform_in_Jerusalem.png",
    "assets/Vedas_palm_leaf_manuscript.jpg",
    "assets/8_Ox_Scapula_Oracle_Bone_by_Zhēng_爭.png",
    "assets/9_Bronze_Fāng_Zūn_Ritual_Wine_Container.png",
    "assets/Dipylon_Inscription.JPG",
    "assets/Edicts_of_Ashoka.jpg",
    "assets/Lead_Piece_from_Pujol.png",
    "assets/Glyph_Block_8_from_San_Bartolo.jpeg",
    "assets/Mawangdui_Silk_Text_Tao_Te_Ching.jpeg",
    "assets/Rosetta_Stone.jpeg",
    "assets/Great_Psalms_Scroll_Page.jpg",
    "assets/11_ Gandhāran_Buddhist_Birchbark_Scroll.jpg",
    "assets/Vindolanda_Tablet.jpg",
    "assets/Svingerud_Runestone.jpg",
    "assets/Pi_Yu_Jing.jpg",
    "assets/Bath_Curse_Tablet.jpg",
    "assets/Birmingham_Quran_manuscript.jpg",
    "assets/Diamond_Sutra_from_Tang_dynasty.jpg",
    "assets/Missal_of_Silos.jpg",
    "assets/Dresden_Codex.png",
    "assets/Birch_Bark_Letter_No_202.jpg",
    "assets/Jikji_pages.jpg",
    "assets/Gutenberg_Bible.jpg"
]

var icon_names = [
    "icons/1_Kish_Tablet.png",
    "icons/2_Narmer_Palette.jpeg",
    "icons/Instructions_of_Shurrupak.jpg",
    "icons/4_Diary_of_Merer.jpeg",
    "icons/3_Palermo_Stone.jpeg",
    "icons/5_Istanbul_2461.jpeg",
    "icons/Code_of_Hammurabi.png",
    "icons/6_Complaint_tablet_to_Ea-nāṣir.jpeg",
    "icons/Gilgamesh_Dream_Tablet.jpg",
    "icons/7_Akkadian_Cuneiform_in_Jerusalem.jpeg",
    "icons/Vedas_palm_leaf_manuscript.jpg",
    "icons/8_Ox_Scapula_Oracle_Bone_by_Zhēng_爭.jpeg",
    "icons/9_Bronze_Fāng_Zūn_Ritual_Wine_Container.jpeg",
    "icons/Dipylon_Inscription.JPG",
    "icons/Edicts_of_Ashoka.jpg",
    "icons/Lead_Piece_from_Pujol.png",
    "icons/Glyph_Block_8_from_San_Bartolo.jpeg",
    "icons/Mawangdui_Silk_Text_Tao_Te_Ching.jpeg",
    "icons/Rosetta_Stone.jpeg",
    "icons/10_Great_Psalms_Scroll.jpeg",
    "icons/11_ Gandhāran_Buddhist_Birchbark_Scroll.jpg",
    "icons/Vindolanda_Tablet.jpg",
    "icons/Svingerud_Runestone.jpg",
    "icons/Pi_Yu_Jing.jpg",
    "icons/Bath_Curse_Tablet.jpg",
    "icons/Birmingham_Quran_manuscript.jpg",
    "icons/Diamond_Sutra_from_Tang_dynasty.jpg",
    "icons/Missal_of_Silos.jpg",
    "icons/Dresden_Codex.png",
    "icons/Birch_Bark_Letter_No_202.jpg",
    "icons/Jikji_pages.jpg",
    "icons/Gutenberg_Bible.jpg"
]